image: Visual Studio 2019

configuration: Release
platform: Win32

build_script:
  - msbuild projects/vs2019/projects.sln /t:hldll;hl_cdll /p:Configuration=Release /p:Platform=Win32 /p:PostBuildEventUseInBuild=false /verbosity:minimal

artifacts:
  - path: projects\vs2019\Release\hl.dll
    name: hl-server-dll
  - path: projects\vs2019\Release\client.dll
    name: hl-client-dll

deploy: off
