image: Visual Studio 2019

configuration: Release
platform: Win32

build:
  project: projects/vs2019/projects.sln
  verbosity: minimal
  msbuild_options: /p:PostBuildEventUseInBuild=false

artifacts:
  - path: projects\vs2019\Release\hl.dll
    name: hl-server-dll
  - path: projects\vs2019\Release\client.dll
    name: hl-client-dll

deploy: off
